const app=document.getElementById("app");const socket=io();let me=JSON.parse(localStorage.getItem("pulse_me")||"null");let users=[];let messages=[];let friends=JSON.parse(localStorage.getItem("pulse_friends")||"[]");let stream=null;let audioCtx=null;let analyser=null;let talking=false;let cam=false;let screenStream=null;
function av(u,big=false){return u.avatar?`<img class="avatar ${big?"big":""}" src="${esc(u.avatar)}">`:`<div class="avatar ${big?"big":""}">${esc((u.name||"?").slice(0,2).toUpperCase())}</div>`}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function login(){app.innerHTML=`<main class="auth"><section class="card"><div class="logo">⚡ Pulse</div><div class="sub">Seu chat privado com seus amigos.</div><form id="f"><div class="field"><label>Nome</label><input id="n" required minlength="2"></div><div class="field"><label>Senha</label><input id="p" type="password" required></div><div id="e" class="err"></div><button class="primary">Entrar</button></form></section></main>`;f.onsubmit=e=>{e.preventDefault();me={name:n.value.trim(),avatar:localStorage.getItem("pulse_avatar_"+n.value.trim())||""};localStorage.setItem("pulse_me",JSON.stringify(me));start()}}
function start(){socket.emit("join",me);render()}
function render(){app.innerHTML=`<div class="layout"><aside class="servers"><button class="server">P</button></aside><main class="main"><header class="head">💬 Geral <button class="callbtn" id="call" style="margin-left:auto">Entrar na call</button></header><div class="messages" id="msgs"></div><div class="composer"><form id="mf"><input id="mi" placeholder="Digite uma mensagem..."><button class="send">Enviar</button></form></div></main><aside class="right"><h3>Amigos / online</h3><button class="callbtn" id="add" style="width:100%;padding:9px">Adicionar pessoa</button><div id="people"></div><hr><button class="callbtn" id="profile" style="width:100%;padding:9px">Meu perfil</button></aside></div><section class="call" id="callbox"><div class="calltitle">🎙️ Chamada</div><div class="tiles" id="tiles"></div><div class="controls"><button class="ctrl" id="mic">🎙️ Mic</button><button class="ctrl" id="camera">📹 Câmera</button><button class="ctrl" id="share">🖥️ Tela</button><button class="ctrl danger" id="leave">Sair</button></div></section>`;
mf.onsubmit=e=>{e.preventDefault();if(mi.value.trim()){socket.emit("message",mi.value.trim());mi.value=""}};call.onclick=joinCall;leave.onclick=leaveCall;mic.onclick=toggleMic;camera.onclick=toggleCam;share.onclick=shareScreen;add.onclick=addFriend;profile.onclick=editProfile;draw();drawPeople()}
function draw(){msgs.innerHTML=messages.map(m=>`<div class="msg">${av(m)}<div><div class="msgname">${esc(m.name)}<span class="time">${m.time}</span></div><div class="text">${esc(m.text)}</div></div></div>`).join("")||`<div style="text-align:center;color:#747b8b;margin-top:30vh">Nenhuma mensagem ainda.</div>`;msgs.scrollTop=msgs.scrollHeight}
function drawPeople(){people.innerHTML=users.map(u=>`<div class="person" id="person_${u.id}">${av(u)}<span>${esc(u.name)}</span></div>`).join("")}
socket.on("users",u=>{users=u;drawPeople()});socket.on("message",m=>{messages.push(m);draw()});
function addFriend(){let name=prompt("Digite o nome exato da pessoa:");if(!name)return;if(!friends.includes(name))friends.push(name);localStorage.setItem("pulse_friends",JSON.stringify(friends));alert(name+" foi adicionado à sua lista!")}
function editProfile(){let name=prompt("Nome:",me.name)||me.name;let avatar=prompt("URL da sua foto de perfil (opcional):",me.avatar||"")??me.avatar;me={name,avatar};localStorage.setItem("pulse_me",JSON.stringify(me));localStorage.setItem("pulse_avatar_"+name,avatar);socket.emit("join",me);render()}
async function joinCall(){callbox.classList.add("show");tiles.innerHTML=users.map(u=>`<div class="tile" id="tile_${u.id}">${av(u,true)}<div>${esc(u.name)}</div></div>`).join("")+`<div class="tile" id="tile_me">${av(me,true)}<div>${esc(me.name)} (você)</div></div>`;try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});setupAnalyser();socket.emit("call-state",{mic:true,cam:false})}catch(e){alert("Permita o microfone no navegador para entrar na call.")}}
function setupAnalyser(){audioCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=256;let src=audioCtx.createMediaStreamSource(stream);src.connect(analyser);let data=new Uint8Array(analyser.frequencyBinCount);function loop(){if(!analyser)return;analyser.getByteFrequencyData(data);let avg=data.reduce((a,b)=>a+b,0)/data.length;let now=avg>18;if(now!==talking){talking=now;document.getElementById("tile_me")?.querySelector(".avatar")?.classList.toggle("green",now);socket.emit("call-state",{talking:now,mic:true,cam})}requestAnimationFrame(loop)}loop()}
function toggleMic(){if(!stream)return;let t=stream.getAudioTracks()[0];t.enabled=!t.enabled;mic.textContent=t.enabled?"🎙️ Mic":"🔇 Mutado";if(!t.enabled){talking=false;document.querySelector("#tile_me .avatar")?.classList.remove("green")}socket.emit("call-state",{mic:t.enabled,cam,talking:false})}
async function toggleCam(){if(!stream)return;try{if(!cam){let v=await navigator.mediaDevices.getUserMedia({video:true});v.getVideoTracks()[0].enabled=true;cam=true;camera.textContent="📹 Câmera ON"}else{cam=false;camera.textContent="📹 Câmera"}socket.emit("call-state",{mic:stream.getAudioTracks()[0]?.enabled,cam})}catch(e){alert("Não foi possível acessar a câmera.")}}
async function shareScreen(){try{screenStream=await navigator.mediaDevices.getDisplayMedia({video:true});share.textContent="⛔ Parar tela";screenStream.getVideoTracks()[0].onended=()=>{share.textContent="🖥️ Tela";screenStream=null}}catch(e){}}
function leaveCall(){if(stream)stream.getTracks().forEach(t=>t.stop());if(screenStream)screenStream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close();stream=null;analyser=null;callbox.classList.remove("show");socket.emit("call-state",{mic:false,cam:false,talking:false})}
socket.on("call-state",s=>{let el=document.querySelector(`#tile_${s.id} .avatar`);if(el)el.classList.toggle("green",!!s.talking)});
if(me)start();else login();